
#ifndef SNAPMAKER_CONFIG_H_
#define SNAPMAKER_CONFIG_H_

#include "MapleFreeRTOS1030.h"

// FreeRTOS tasks configuration
#define SNAPMAKER_APP_PRIORITY        (3)

#define MARLIN_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define MARLIN_TASK_STACK_SIZE        (2048)  // 8kBytes

#define SACP_RECV_TASK_PRIORITY       SNAPMAKER_APP_PRIORITY
#define SACP_RECV_TASK_STACK_SIZE     (256)
#define SACP_EVENT_TASK_PRIORITY      SNAPMAKER_APP_PRIORITY
#define SACP_EVENT_TASK_STACK_SIZE    (512)

#define SSTP_CAMERA_RECV_TASK_PRIORITY     SNAPMAKER_APP_PRIORITY
#define SSTP_CAMERA_RECV_TASK_STACK_SIZE   (256)
#define SSTP_CAMERA_EVENT_TASK_PRIORITY    SNAPMAKER_APP_PRIORITY
#define SSTP_CAMERA_EVENT_TASK_STACK_SIZE  (256)

#define SSTP_MODULE_RECV_TASK_PRIORITY     SNAPMAKER_APP_PRIORITY
#define SSTP_MODULE_RECV_TASK_STACK_SIZE   (256)
#define SSTP_MODULE_EVENT_TASK_PRIORITY    SNAPMAKER_APP_PRIORITY
#define SSTP_MODULE_EVENT_TASK_STACK_SIZE  (256)

#define SM_CAN_RECV_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define SM_CAN_RECV_TASK_STACK_SIZE        (256)
#define SM_CAN_RECV_EVENT_PRIORITY         SNAPMAKER_APP_PRIORITY
#define SM_CAN_RECV_EVENT_STACK_SIZE       (256)

#define SM_MAC_RECV_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define SM_MAC_RECV_TASK_STACK_SIZE        (256)
#define SM_MAC_RECV_EVENT_PRIORITY         SNAPMAKER_APP_PRIORITY
#define SM_MAC_RECV_EVENT_STACK_SIZE       (256)

#endif  // #ifndef SNAPMAKER_CONFIG_H_
