
#ifndef SNAPMAKER_CONFIG_H_
#define SNAPMAKER_CONFIG_H_

#include "MapleFreeRTOS1030.h"

// FreeRTOS tasks configuration
#define SNAPMAKER_APP_PRIORITY        (3)

#define MARLIN_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define MARLIN_TASK_STACK_SIZE        (2048)  // 8kBytes

#define SACP_RECV_TASK_PRIORITY       SNAPMAKER_APP_PRIORITY
#define SACP_RECV_TASK_STACK_SIZE     (256)
#define SACP_EVENT_TASK_PRIORITY      SNAPMAKER_APP_PRIORITY
#define SACP_EVENT_TASK_STACK_SIZE    (512)

#define SSTP_CAMERA_RECV_TASK_PRIORITY     SNAPMAKER_APP_PRIORITY
#define SSTP_CAMERA_RECV_TASK_STACK_SIZE   (256)
#define SSTP_CAMERA_EVENT_TASK_PRIORITY    SNAPMAKER_APP_PRIORITY
#define SSTP_CAMERA_EVENT_TASK_STACK_SIZE  (256)

#define SSTP_MODULE_RECV_TASK_PRIORITY     SNAPMAKER_APP_PRIORITY
#define SSTP_MODULE_RECV_TASK_STACK_SIZE   (256)
#define SSTP_MODULE_EVENT_TASK_PRIORITY    SNAPMAKER_APP_PRIORITY
#define SSTP_MODULE_EVENT_TASK_STACK_SIZE  (256)

#define SM_CAN_RECV_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define SM_CAN_RECV_TASK_STACK_SIZE        (256)
#define SM_CAN_RECV_EVENT_PRIORITY         SNAPMAKER_APP_PRIORITY
#define SM_CAN_RECV_EVENT_STACK_SIZE       (256)

#define SM_MAC_RECV_TASK_PRIORITY          SNAPMAKER_APP_PRIORITY
#define SM_MAC_RECV_TASK_STACK_SIZE        (256)
#define SM_MAC_RECV_EVENT_PRIORITY         SNAPMAKER_APP_PRIORITY
#define SM_MAC_RECV_EVENT_STACK_SIZE       (256)


// task parameters for can event handler task
#define CAN_EVENT_HANDLER_PRIORITY    (3)
#define CAN_EVENT_HANDLER_STACK_DEPTH (512)

// task parameters for can receive handler task
#define CAN_RECEIVE_HANDLER_PRIORITY    (3)
#define CAN_RECEIVE_HANDLER_STACK_DEPTH (512)

// task parameters for marlin loop task
#define MARLIN_LOOP_TASK_PRIO (3)
#define MARLIN_LOOP_STACK_DEPTH 1024

// task parameters for hmi task
#define HMI_TASK_PRIO (3)
#define HMI_TASK_STACK_DEPTH 512

// task parameters for heartbeat task
#define HB_TASK_PRIO (3)
#define HB_TASK_STACK_DEPTH 512

// priority for UARTs
#define EXECUTOR_SERIAL_IRQ_PRIORITY 7
#define HMI_SERIAL_IRQ_PRIORITY 8
#define MARLIN_SERIAL_IRQ_PRIORITY 9


#define DEFAUT_LEVELING_HEIGHT  9 // uint: mm

#define MODULE_LINEAR_PITCH_20        160
#define MODULE_LINEAR_PITCH_8         400


//FLASH layout
#define FLASH_SIZE      (1024*1024)
#define BOOT_CODE_SIZE	(32*1024)
#define BOOT_PARA_SIZE	(4*1024)
#define MARLIN_POWERPANIC_SIZE  (6*1024)
//#define MARLIN_EEPROM_SIZE (4*1024)
#define UPDATE_CONTENT_INFO_SIZE (2*1024)
#define MARLIN_CODE_SIZE	((FLASH_SIZE - BOOT_CODE_SIZE - BOOT_PARA_SIZE - MARLIN_POWERPANIC_SIZE - UPDATE_CONTENT_INFO_SIZE) / 2)


#endif  // #ifndef SNAPMAKER_CONFIG_H_
